modLoader = "javafml"
loaderVersion = "[4,)"

[[mods]]
modId = "icyincitement"
version = "${version}"
displayName = "Icy Incitement"
description = "Some useful snowy tools!"

[properties]
"connector:placeholder" = true

[[dependencies.icyincitement]]
modId = "connector"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.icyincitement]]
modId = "fabric_api"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"